config/routes.rb
Rails.application.routes.draw do
  get 'admin/blogs'
  get 'admin/resources'
  get 'admin/subcategories'
  get 'admin/subscribers'
  resources :blogs
  resources :resources
  resources :subscribers
  resources :subcategories
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/store', as: 'spree'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #  COSMETICS
  get 'home/index'
  root 'home#index'

  get 'home/info'
  get 'home/export'
  get 'home/kits'

  get 'kits/XR250_XR400'
  get 'kits/XR600'
  get 'kits/XR650L'
  get 'kits/polaris_key_covers'
  get 'kits/replacement'
  get 'kits/rear_fenders_1'
  get 'kits/rear_fenders_2'
  get 'kits/graphics'

  get 'other/xr400mx'

  # PHOTOS
  resources :photos
  put "photos/:id/approve" => "photos#approve", as: "approve_photo"
  put "photos/:id/unapprove" => "photos#unapprove", as: "unapprove_photo"

  # CONTACT US
  resources :contacts
  put "contacts/:id/archive" => "contacts#archive", as: "archive_contact"
  put "contacts/:id/unarchive" => "contacts#unarchive", as: "unarchive_contact"


end

app/views/admin/blogs.html.erb
<header
  class="bgimage"
  style="background: url(<%= asset_url("tiretracks.jpg") %>); height: 200px">
</header>

<div class="background-white py-5">
  <div class="container text-center pb-2">

    <header class="text-center mb-4">
      <p>
        <%= link_to 'New Blog', new_blog_path %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to 'Blog Homepage', blogs_path %>
      </p>
      <h1 class="text-center font-weight-bold">Blog Manager</h1>
    </header>


    <section class="text-center aloop-card"> <!-- blogs -->
      <h2>Blogs</h2>
      <div class="table-responsive" style="width: 100%">
        <table id="dtBasicExample" class="table table-striped table-bordered" width="100%">
          <thead>
            <tr>
              <th>Actions</th>
              <th>Title</th>
              <th>Published</th>
              <th>Author</th>
              <th>Subcategory</th>
              <th>Video</th>
            </tr>
          </thead>

          <tbody class="text-left">
            <% @blogs.each do |blog| %>
              <tr>
                <td class="text-center">
                  <%= link_to '✎', edit_blog_path(blog), class: "pr-1" %>
                  <%= link_to '✘', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
                <td>
                  <%= link_to blog.title, blog %>
                </td>

                <td><% if blog.published %><%= blog.published_at.strftime("%b %e, %Y") %><% else %>No<% end %></td>

                <td><%= Spree::User.find(blog.spree_user_id).first_name %> <%= Spree::User.find(blog.spree_user_id).last_name %></td>
                <td>
                  <% if blog.subcategory %>
                    <%= link_to Subcategory.find(blog.subcategory_id).name, Subcategory.find(blog.subcategory_id) %><br>
                  <% end %>
                </td>
                <td class="text-center"><% if blog.video_url != "" %>✔<% end %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div> <!-- table responsive -->
    </section>






    <section id="author">
      <h2 style="padding-bottom: 0; margin-bottom: 0">My Author Info</h2>
      <%= render partial: "users/biobox", locals: { user: Spree::User.find(current_spree_user.id) } %>
      <p class="text-center">You'll be able to update this yourself soon. For now, contact the Lizbot. Sorry.</p>
    </section>

</div> <!-- background -->





<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/admin/resources.html.erb
<header
  class="bgimage"
  style="background: url(<%= asset_url("tiretracks.jpg") %>); height: 200px">
</header>

<div class="background-white py-5">
  <div class="container text-center pb-2">
    <header class="text-center mb-4">
      <p>
        <%= link_to 'New Lead Magnet', new_resource_path %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to 'Public Resources Page', resources_path %>
      </p>
      <h1 class="text-center font-weight-bold">Lead Magnet Manager</h1>

    </header>

    <section class="text-center my-5"> <!-- blogs -->
      <div class="container">  <!-- container -->


        <div class="table-responsive" style="width: 100%">
          <table id="dtBasicExample" class="table table-striped table-bordered" width="100%">
            <thead>
              <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Active</th>
              </tr>
            </thead>

            <tbody>
              <% @resources.each do |resource| %>
                <tr>
                  <td style="text-align: top">
                    <%= link_to resource.title, resource %>
                    (
                    <span style="font-size: 20px">
                      <%= link_to "✐", edit_resource_path(resource) %>
                    </span>
                    <span style="font-size: 16px">
                      <%= link_to "⌫", resource, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </span>
                    )
                  </td>
                  <td><%= link_to resource.classification, url_for(resource.document) %></td>

                  <td><% if resource.active %>✓<% end %></td>

                </tr>
              <% end %>
            </tbody>
          </table>
        </div> <!-- table responsive -->
      </section>


  </div> <!-- container -->
</div> <!-- background -->



<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/admin/subcategories.html.erb
<header
  class="bgimage"
  style="background: url(<%= asset_url("tiretracks.jpg") %>); height: 200px">
</header>

<div class="background-white pb-5 pt-3">
  <div class="container text-center pb-2">

    <header class="">
      <p class="text-center">
        <%= link_to 'New Subcategory', new_subcategory_path %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        <%= link_to 'Blogs Manager', admin_blogs_path %>
      </p>

      <h1 class="font-weight-bold text-center">Subcategories</h1>
    </header>

    <section class="text-center mb-5 my-"> <!-- blogs -->
      <div class="container">  <!-- container -->

        <div class="stb-box">
          <div class="table-responsive" style="width: 100%">
            <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
              <thead>
                <tr>
                  <th class="th-sm">Name</th>
                  <th class="th-sm">Blogs</th>
                  <th class="th-sm">Lead Magnets</th>
                  <th class="th-sm">Active</th>
                </tr>
              </thead>

              <tbody>
                <% @subcategories.each do |subcategory| %>
                  <tr>
                    <td class="text-left">
                      <%= link_to subcategory.name, subcategory %>
                      <%= link_to '✎'.html_safe, edit_subcategory_path(subcategory), class: "color-blue" %>
                      <%= link_to '✘'.html_safe, subcategory, method: :delete, data: { confirm: 'Are you sure?' }, class: "color-pink" %>
                    </td>
                    <td>
                      <% n = 0 %>
                      <% Blog.all.each do |blog| %>
                        <% if blog.subcategory == subcategory %>
                          <% n += 1 %>
                        <% end %>
                      <% end %>
                      <%= n %>
                    </td>
                    <td>
                      <% n = 0 %>
                      <% Resource.all.each do |resource| %>
                        <% if resource.subcategory == subcategory %>
                          <% n += 1 %>
                        <% end %>
                      <% end %>
                      <%= n %>
                    </td>

                    <td><% if subcategory.active %>✔<% end %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div> <!-- table responsive -->
        </div> <!-- box -->

      </div> <!-- container -->
    </section>



  </div> <!-- container -->
</div> <!-- background -->




<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/admin/subscribers.html.erb
<header
  class="bgimage"
  style="background: url(<%= asset_url("tiretracks.jpg") %>); height: 200px">
</header>

<div class="background-white py-5">
  <div class="container text-center pb-2">
    <main class="py-5 container">

      <header class="text-center">
        <h1>Subscribers</h1>
      </header>


      <div class="">
        <h2>Subscribers by Resource</h2>
        <section id="by-resource" class="pb-5">
          <table class="alternating-table">
            <thead>
              <tr>
                <th scope="col">Resource Name</th>
                <th scope="col"># Subscribed</th>
              </tr>
            </thead>

            <tbody>
              <% Resource.all.each do |resource| %>
                <tr>
                  <% subscribed = 0 %>

                  <% @subscribers.each do |sub| %>
                    <% if sub.resource_id_array.include?(resource.id.to_s) %>
                      <% subscribed += 1 %>
                    <% end %>
                  <% end %>

                  <td><%= link_to resource.title, resource %></td>
                  <td><%= subscribed %></td>
                <tr>
              <% end %>
            </tbody>
          </table>
        </section>  <!-- resources -->


        <% unsubscribed = Subscriber.where(unsubscribed: true) %>

        <h2>Subscribers List (<%= @subscribers.count - unsubscribed.count %>)</h2>
        <section>
          <table class="alternating-table">
            <thead>
              <tr>
                <th scope="col">Date</th>
                <th scope="col">First Name</th>
                <th scope="col">Email</th>
                <th scope="col">Resources</th>
                <th scope="col">Customer</th>
                <th scope="col">Unsub</th>
                <th scope="col">Delete</th>
              </tr>
            </thead>

            <tbody>
              <% @subscribers.each do |subscriber| %>
                <% memberMatch = false %>
                <% Spree::User.all.each do |u| %>
                  <% if u.email == subscriber.email %>
                    <% memberMatch = true %>
                  <% end %>
                <% end %>
                <tr>
                  <td><%= subscriber.created_at.strftime("%m/%d/%Y") %></td>
                  <td><%= subscriber.first_name %></td>
                  <td><%= subscriber.email %></td>
                  <td><% subscriber.resource_id_array.each do |res_id| %><%= Resource.find(res_id).title %><br><% end %></td>
                  <td class="text-center"><% if memberMatch %>✔<% end %></td>
                  <td class="text-center"><% if subscriber.unsubscribed %>✘<% end %></td>
                  <td class="text-center"><%= link_to '✘', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </section> <!-- by-name -->
      </div> <!-- pb-4 -->
    </main>


  </div> <!-- container -->
</div> <!-- background -->






<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>