config/routes.rb
Rails.application.routes.draw do
  get 'admin/blogs'
  get 'admin/resources'
  get 'admin/subcategories'
  get 'admin/subscribers'
  resources :blogs
  resources :resources
  resources :subscribers
  resources :subcategories
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/store', as: 'spree'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #  COSMETICS
  get 'home/index'
  root 'home#index'

  get 'home/info'
  get 'home/export'
  get 'home/kits'

  get 'kits/XR250_XR400'
  get 'kits/XR600'
  get 'kits/XR650L'
  get 'kits/polaris_key_covers'
  get 'kits/replacement'
  get 'kits/rear_fenders_1'
  get 'kits/rear_fenders_2'
  get 'kits/graphics'

  get 'other/xr400mx'

  # PHOTOS
  resources :photos
  put "photos/:id/approve" => "photos#approve", as: "approve_photo"
  put "photos/:id/unapprove" => "photos#unapprove", as: "unapprove_photo"

  # CONTACT US
  resources :contacts
  put "contacts/:id/archive" => "contacts#archive", as: "archive_contact"
  put "contacts/:id/unarchive" => "contacts#unarchive", as: "unarchive_contact"


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @latest_blog = Blog.where(published: true).order("created_at DESC").limit(1).first
    @videos = Blog.where.not(video_url: "").limit(12)
  end

  def info
  end

  def export
  end

  def kits
  end
end

app/views/home/_cta.html.erb
<div class="contact-formats text-center">
	<div class="black-box background-white">
		<h2 style="font-size: 30px; margin-bottom: 20px">There are 3 ways to order from&nbsp;Aloop</h2>

		<div class="row">
			<div class="col-sm-4">
				<%= link_to spree_path, class: "no-underline" do %>
					<h2>Order<br class="hidden-lg"> Online</h2>
					<i class="icon ion-ios-cart"></i>
					<p>You can order any of our products on our online store.</p>
				<% end %>
			</div> <!-- contact format box -->

			<div class="col-sm-4">
				<a href="mailto:sales@aloop.com" class="no-underline">
					<h2>Send<br class="hidden-lg"> Email</h2>
					<i class="icon ion-paper-airplane"></i>
					<p>We welcome orders, reviews, and questions by email.</p>
				</a>
			</div> <!-- contact format box -->

			<div class="col-sm-4">
				<a href="#address-popup" class="open-popup-link no-underline">
					<h2>Postal<br class="hidden-lg"> Service</h2>
					<i class="icon ion-email"></i>
					<p>You can post orders as well as any questions you might have.</p>
				</a>
			</div> <!-- contact format box -->

		</div> <!-- row -->
	</div> <!-- column -->
</div> <!-- contact formats -->






<div id="address-popup" class="white-popup mfp-hide">
	<div class="text-center">
		<h2>Aloop Offroad</h2>
		<h4>PO Box 412
		<br>Sedalia, CO 80135, USA</h4>
    </div>
</div> <!-- address popup -->




<script type="text/javascript">
	$('.open-popup-link').magnificPopup({
	  type:'inline',
	  midClick: true // Allow opening popup on middle mouse click. Always set it to true if you don't provide alternative source in href.
	});
</script>

app/views/home/export.html.erb
<header class="bgimage" style="background: url(<%= asset_url("polaris_4.jpg") %>)">
  <div class="index-only-text shadow-bottom w-100">
    <div class="container py-3">
      <h3>Exports</h3>
    </div> <!-- container -->
  </div> <!-- index text row -->
</header>





<div class="row text-center py-5">
	<div class="container">
		<h3 class="font-weight-bold">Overseas orders are no problem!</h3>
    <h4>We've sold thousands of our Aloop 4SMX kits to customers in over 40 countries! Most shipments are sent via US Mail Global Express Mail, and can arrive in under 1 week, no matter where in the world you live.</h4>

    <h3 style="font-weight: 900; margin-top: 0px"><%= link_to new_contact_path, class: "no-underline" do %>Contact us today for a shipping&nbsp;quote!<% end %></h3>

	</div> <!-- container -->
</div> <!-- row -->





<div class="text-center background-white shadow-top py-5">
  <div class="container">
    <div class="row justify-content-center">

    	<div class="col-12">
    		<h5>We usually ship overseas orders via US Mail Global Express Mail service. It takes about 3-5 days to reach Europe and 7-10 days to reach Asia and Australia. Cost for Global Express Mail shipping is usually about&nbsp;$150&nbsp;USD&nbsp;per&nbsp;kit.</h5>
        <h5>The kit comes in two boxes so it does not travel as an oversize parcel. With Global Express Mail we can track the progress of the packages and it's been a very reliable method to get our products overseas.</h5>
    		<h5><strong>We also have a distributor in Japan that stocks&nbsp;Aloop&nbsp;4SMX&nbsp;kits:</strong></h5>
    	</div> <!-- column -->

    	<%= link_to "http://www.chsports.com", class: "no-underline" do %>
    		<div class="col-12 black-box hover" style="margin-left: 10px">
    			<h2 style="font-size: 40px">Japan</h2>
    			<%= image_tag "japan.jpg", style: "width: 200px; margin: 40px 0 35px 0", alt: "Chane Sports" %>
    			<h4>Chane Sports</h4>
    		</div> <!-- distributor link -->
    	<% end %>

    </div> <!-- row -->
  </div> <!-- container -->
</div> <!-- white bg -->

app/views/home/index.html.erb
<header class="bgimage" style="background: url(<%= asset_url("polaris_6.jpg") %>)">
  <div class="index-only-text bottom-shadow w-100">
    <div class="container py-3">
      <h3>"The Honda that Honda should have built..."</h3>
    </div> <!-- container -->
  </div> <!-- index text row -->
</header>



<section class="row text-center py-5">
	<div class="container">
		<h2>No other single modification can give you such an immediate gain in handling, performance, and&nbsp;style!</h2>
    <%= link_to "See Our Customer Photos", photos_path, class: "btn cta" %>
	</div> <!-- container -->
</section> <!-- row -->



<section class="background-white shadow-top bottom-shadow py-5">
  <div class="container">
    <div class="row">

  		<div class="col-sm-6">
  			<h3>A Totally New Concept.</h3>
  			<p>“The Honda that Honda should have built” Aloop's 4SMX tank/seat kit is a totally new concept in Motocross racing accessories. This kit features a smaller than stock 2.0 gallon plastic fuel tank, a new seat based around the CR250 style seating position, and it utilizes shrouds from a CR to enhance engine cooling and overall style.</p>
  		</div> <!-- column -->

  		<div class="col-sm-6">
  			<h3>Ready to Bolt On.</h3>
  			<p>The Aloop 4SMX Kit uses your stock petcock, fuel cap and mounting hardware. The new tank includes a right side petcock for better fuel flow. Total fuel capacity is only .8 gallons less than stock, but in a greatly improved ergonomics package. A great looking Aloop graphics set and non-slip seat cover round out the kit. All parts made in the USA. Get one and go fast!</p>
  		</div> <!-- column -->


  		<div class="col-12">
  			<h3>No “Humpback” Seat Like the Awkward Stock Setup.</h3>
  			<p>With the Aloop 4SMX kit, the rider can sit a full 3" further forward on the narrow, flat seat, without encountering the awkward hump of the stock setup. The new fuel tank is 3" narrower than stock tank, and the new seat places the rider 3/4" higher as well for a greatly improved ergonomic feel. CR250 style radiator shrouds direct cooling air to the engine, and provide a place for mounting of additional oil coolers. Best of all, the new fuel tank is dramatically slimmer, and riders will find it much easier to grip the tank in the rough sections. This improves the handling and you will easily ride your machine faster. A Motocross Seat Tank kit may just be the most noticeable mod you make for your race bike.</p>
  		</div> <!-- column -->

    </div> <!-- info row -->
  </div> <!-- info row -->
</section> <!-- container -->




<section class="row text-center py-5">
	<div class="container">
		<h2>See our full range of products</h2>
    <%= link_to "Go to Store", main_app.spree_path, class: "btn cta" %>
	</div> <!-- container -->
</section> <!-- row -->


<% if @latest_blog %>
  <section class="row py-5 background-white shadow-top bottom-shadow">
  	<div class="container">
  		<h2 class="text-center"><%= @latest_blog.title %></h2>
      <div id="blog-body"><%= @latest_blog.body.html_safe %></div>
      <div class="text-center">
        <%= link_to "More from the Blog", blogs_path, class: "btn cta" %>
      </div>
  	</div> <!-- container -->
  </section> <!-- row -->
<% end %>






<% if @videos != [] %>
  <section class="row py-5 ">
  	<div class="container">
      <h2 class="text-center pb-3">Videos</h2>
      <div class="row">
        <% @videos.each do |video| %>
          <div class="col-sm-6 col-md-4 video-grid">
            <%= video.video_url.html_safe %>
          </div> <!-- col -->
        <% end %>
      </div> <!-- row -->
  	</div> <!-- container -->
  </section> <!-- row -->
<% end %>




<section class="row py-5 background-white shadow-top bottom-shadow">
	<div class="container">
		<h2 class="text-center pb-4">From the 'Gram</h2>

    <!-- Place <div> tag where you want the feed to appear -->
    <div id="curator-feed-aloop-offroad-layout"><a href="https://curator.io" target="_blank" class="crt-logo crt-tag">Powered by Curator.io</a></div>
    <!-- The Javascript can be moved to the end of the html page before the </body> tag -->
    <script type="text/javascript">
    /* curator-feed-aloop-offroad-layout */
    (function(){
    var i, e, d = document, s = "script";i = d.createElement("script");i.async = 1;
    i.src = "https://cdn.curator.io/published/65414202-ebc8-4b03-90ae-5b54dab3ee4d.js";
    e = d.getElementsByTagName(s)[0];e.parentNode.insertBefore(i, e);
    })();
    </script>

	</div> <!-- container -->
</section> <!-- row -->

app/views/home/info.html.erb
<header class="bgimage" style="background: url(<%= asset_url("polaris_2.jpg") %>)">
  <div class="index-only-text bottom-shadow w-100">
    <div class="container py-3">
      <h3>Information & FAQ</h3>
    </div> <!-- container -->
  </div> <!-- index text row -->
</header>





<div class="row text-center py-5">
	<div class="container">
		<h3>Aloop sells and ships our products worldwide. We've sent Aloop kits to thousands of riders in over 50 countries, and the list grows almost&nbsp;every&nbsp;day.</h3>
    <h3><strong>Here's a letter from a happy customer in Spain:</strong></h3>

    <div class="sticky-note">
  		<span style="display: inline-block; position: relative; width: 1%; vertical-align: middle; height: 350px"></span>
  		<div class="sticky-note-text"><em>
  			<p>The kit arrived by late Friday, indeed much sooner than expected, so I must say I’m quite impressed by shipping service. I’ve been also quite impressed by the general quality of fit, finish an engineering of the A-Loop kit. Thanks to it I have an all together new bike!</p>
  			<p>I decided to take my time and enjoy the work, so I spent best part of the weekend mounting the kit. Thanks to the sense of humour of the instructions I must say it was a double enjoyment. In short, thanks for an outstanding product and a no less outstanding service.</p>
  			<p class="text-right">Kind regards from Spain, Fernando G.</p>
  		</em></div> <!-- text div -->
  	</div> <!-- sticky note -->

	</div> <!-- container -->
</div> <!-- row -->







<div class="row FAQ background-white top-shadow py-5">
	<div class="container">
		<h3 class="text-center">Here are some questions and answers about the Aloop 4SMX Seat/Tank Kit.</h3>
    <h3 class="text-center"><strong>Click on a question to see the answer.</strong></h3>

		<h4 class="question">What shrouds (radiator plastic) does the Aloop kit use?</h4>
		<p class="hidden">The Aloop 4SMX seat/tank kit uses shrouds from the 1999 CR250 Honda. Currently we are supplying Acerbis brand shrouds with our kits, but you could also use genuine Honda shrouds, or even UFO or some other brand. Any shrouds meant to fit the 1999 CR250 should fit our kit.  We do modify the shrouds slightly to fit our tank though.  Basically the mods consist of cutting off the rear shroud bolt hole and mount, and removing the vertical reinforcing rib on the inside of the shroud. If you're fitting your own replacement shrouds use your original Aloop shroud as a guide.</p>

		<h4 class="question">What graphics will fit the Aloop shrouds?</h4>
		<p class="hidden">Any graphics meant to fit the 1997-1999 Honda CR250 will fit our shrouds. To look at our current Aloop graphics, <%= link_to "click here", kits_graphics_path %>. There is no difference between the graphics for any of our 4SMX kits. The 250, 400, 600 and 650 kits all use the same graphics. The 250/400 kit does use a different seat cover from the 600/650.</p>

		<h4 class="question">What seat covers will fit an Aloop Seat?</h4>
		<p class="hidden">Our seat is designed to have the same profile as a Honda CR250, very long and flat across the top. But since the subframe of an XR is wider than that of a CR, we've made the bottom portion of the seat wide enough to span the wider frame. This means we also had to make a special cover that has a CR profile up top, but has much more material on the sides. Some aftermarket  CR250 seat covers will fit, but only if they have a generous cut with plenty of material to reach our wider seat bottom. You're probably better off buying our replacement Aloop seat cover, since they're definitely wide enough to fit perfectly.</p>

		<h4 class="question">Can I use an Aloop Seat with a stock fuel tank?</h4>
		<p class="hidden">While the Aloop fuel tank and shrouds give our kits their distinctive look, the secret behind an Aloop kit is really the seat. Our flat, CR-style seat profile allows the rider to move much further forward on the bike, placing the rider's weight forward of the footpegs. When you get your weight that far up front it totally changes the way the bike handles. To make our seat so long and flat, we had to design a fuel tank that allowed us to push the seat almost four inches into the space that the stock tank takes up. If you kept the stock tank on your bike, any seat would be pushed up sharply at the front (exactly like your stock XR seat is), because the stock tank has such a big, bulbous hump to it. In order to have that ironing-board profile, you'll need to use the Aloop seat together with the Aloop tank it was made to fit. </p>

		<h4 class="question">Do you sell replacement parts for your kit?</h4>
		<p class="hidden">We sell every part of our XR Seat/Tank kits as a replacement part. <%= link_to "Click here", kits_replacement_path %> to see a part number listing and prices.</p>

		<h4 class="question">Do you ship your Aloop kits worldwide? </h4>
		<p class="hidden">Absolutely! We've sold thousands of Aloop 4SMX kits worldwide to customers in over 40 countries! We are happy to ship direct to you where ever you live.  We usually ship overseas orders via US Mail Global Express Mail service, and it takes about 3-5 days to reach Europe, and 7-10 days to reach Asia and Australia. Cost for Global Express Mail shipping is usually about US$150 per kit. The kit comes in two boxes so it does not travel as an oversize parcel. With Global Express Mail we can both track the progress of the packages, and it's been a very reliable method to get our products overseas.</p>

		<h4 class="question">Do you have any dealers or distributors overseas?</h4>
		<p class="hidden">Yes, check out our <%= link_to "contact page", new_contact_path %> for links to the distributors' websites.</p>

		<h4 class="question">How can I get more fuel capacity out of an Aloop tank?</h4>
		<p class="hidden">One thing you can try is the "boiling water" trick to expand the tank. Empty the tank all the way, then (with tank installed on the bike) fill it to the top with boiling water. Let it sit for a couple of minutes, then inflate the tank gently by mouth thru the vent hose. It'll blow up like a balloon. You don't need much pressure, that's why you do it by mouth and never with compressed air. After you've grown it a bit, (use your judgment about what looks right), then just tie off the vent tube and let it sit overnight. You can use this trick with any plastic tank, and you can usually get up to a quart more capacity without really changing the look of the tank.</p>

		<h4 class="question">My Aloop XR400 seat base has broken, what caused this?</h4>
		<p class="hidden">When you install your seat, please make sure that the two tongues under the middle of the seat are underneath the two wire loops that hold the seat down. If you install the seat wrong and the seat is over these two wire loops, then all you weight is pressing down on the seat tongues and they are sure to break. We have seen this many times even with a stock seat. We recommend that you look at the wire loops and maybe bend them up as tall and straight as they will go. If the seat is installed correctly then there is no stress at all on these two plastic seat tongues and they probably will never break.</p>

	</div> <!-- faq container -->
</div> <!-- faq row -->

<script>
	$(document).ready(function(){
		$(".question").click(function() {
			$(this).next().toggleClass("hidden");
		});
	});
</script>

app/views/home/kits.html.erb
<header class="bgimage" style="background: url(<%= asset_url("polaris_5.jpg") %>)">
  <div class="index-only-text bottom-shadow w-100">
    <div class="container py-3">
      <h3>Aloop Kits</h3>
    </div> <!-- container -->
  </div> <!-- index text row -->
</header>



<div class="container-fluid px-5">
  <div class="row py-5">

    <!-- XR250 -->
    <div class="col-md-4 mb-4">
      <%= link_to kits_XR250_XR400_path do %>
        <div class="card h-100 border-0 shadow">
          <img src="<%= asset_url("kit_1_1.jpg") %>" class="card-img-top" alt="Aloop 4SMX Seat/Tank Kit for XR250 and XR400">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">4SMX Kit for XR250 & XR400</h5>
            <div class="card-text text-black-50">The most popular XR400 performance modification in the world!</div>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    <% end %>


    <!-- XR600 -->
    <div class="col-md-4 mb-4">
      <%= link_to kits_XR600_path do %>
        <div class="card h-100 border-0 shadow">
          <img src="<%= asset_url("kit_2_1.jpg") %>" class="card-img-top" alt="Aloop 4SMX Seat/Tank Kit for XR600">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">4SMX Kit for XR600</h5>
            <div class="card-text text-black-50">This kit fits all XR600's from 1988 thru 2000.</div>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    <% end %>

    <!-- XR600 -->
    <div class="col-md-4 mb-4">
      <%= link_to kits_XR650L_path do %>
        <div class="card h-100 border-0 shadow">
          <img src="<%= asset_url("kit_3_1.jpg") %>" class="card-img-top" alt="Aloop 4SMX Seat/Tank Kit for XR650L">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">4SMX Kit for XR650L</h5>
            <div class="card-text text-black-50">This kit fits all XR600's from 1988 thru 2000.</div>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    <% end %>


    <!-- XR250 -->
    <div class="col-md-6 mb-4">
      <%= link_to kits_polaris_key_covers_path do %>
        <div class="card h-100 border-0 shadow">
          <img src="<%= asset_url("17-19AL_KeyGuard_21.jpg") %>" class="card-img-top" alt="Polaris Key ID Color Coded Key Covers">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">Polaris Key ID Color Coded Key Covers</h5>
            <div class="card-text text-black-50">Aloop’s ‘Key ID’ color coded key covers will help you keep your keys organized.</div>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    <% end %>


    <!-- XR250 -->
    <div class="col-md-6 mb-4">
      <%= link_to kits_graphics_path do %>
        <div class="card h-100 border-0 shadow">
          <img src="<%= asset_url("graphics_gen4.jpg") %>" class="card-img-top" alt="Aloop Graphic Kits">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">Aloop Graphic Kits</h5>
            <div class="card-text text-black-50">Here's a look at our Aloop Graphic kits, past and present...</div>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    <% end %>

    <!-- Rear Fenders 1 -->
    <div class="col-md-4 mb-4">
      <%= link_to kits_rear_fenders_1_path do %>
        <div class="card h-100 border-0 shadow">
          <img src="<%= asset_url("fender_1.jpg") %>" class="card-img-top" alt="Rear Fenders XR250 & XR400">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">Rear Fenders XR250 & XR400</h5>
            <div class="card-text text-black-50">Fits all 1993-2004 Honda XR250R or XR400R models</div>
          </div> <!-- card body -->
        </div> <!-- card -->
      <% end %>
    </div> <!-- col -->


    <!-- Rear Fenders 1 -->
    <div class="col-md-4 mb-4">
      <%= link_to kits_rear_fenders_2_path do %>
        <div class="card h-100 border-0 shadow">
          <img src="<%= asset_url("fender_2.jpg") %>" class="card-img-top" alt="Rear Fenders XR600 & XR650L">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">Rear Fenders XR600 & XR650L</h5>
            <div class="card-text text-black-50">Fits all Honda <strong>XR600R</strong> (1985-2000), <strong>XR650L</strong> (1993-2014), <strong>XR250R</strong> (1986-1995), <strong>XR250L</strong> (1991-1996), and <strong>XR350R</strong> (1985) models.</div>
          </div> <!-- card body -->
        </div> <!-- card -->
      <% end %>
    </div> <!-- col -->


    <!-- Replacement -->
    <div class="col-md-4 mb-4">
      <a href="http://aloop.com/store/t/categories/replacement-parts">
        <div class="card h-100 border-0 shadow">
          <img src="<%= asset_url("metal_background.jpg") %>" class="card-img-top" alt="Replacement Parts">
          <div class="card-body text-center">
            <h5 class="card-title mb-0">Replacement Parts</h5>
            <div class="card-text text-black-50">Need a spare part?  We've got you covered.</div>
          </div> <!-- card body -->
        </div> <!-- card -->
      </a>
    </div> <!-- col -->

  </div> <!-- row -->
</div> <!-- container -->







<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>