config/routes.rb
Rails.application.routes.draw do
  get 'admin/blogs'
  get 'admin/resources'
  get 'admin/subcategories'
  get 'admin/subscribers'
  resources :blogs
  resources :resources
  resources :subscribers
  resources :subcategories
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/store', as: 'spree'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #  COSMETICS
  get 'home/index'
  root 'home#index'

  get 'home/info'
  get 'home/export'
  get 'home/kits'

  get 'kits/XR250_XR400'
  get 'kits/XR600'
  get 'kits/XR650L'
  get 'kits/polaris_key_covers'
  get 'kits/replacement'
  get 'kits/rear_fenders_1'
  get 'kits/rear_fenders_2'
  get 'kits/graphics'

  get 'other/xr400mx'

  # PHOTOS
  resources :photos
  put "photos/:id/approve" => "photos#approve", as: "approve_photo"
  put "photos/:id/unapprove" => "photos#unapprove", as: "unapprove_photo"

  # CONTACT US
  resources :contacts
  put "contacts/:id/archive" => "contacts#archive", as: "archive_contact"
  put "contacts/:id/unarchive" => "contacts#unarchive", as: "unarchive_contact"


end

app/views/resources/_form.html.erb
<div class="blog-form">
  <%= form_with(model: resource, local: true) do |form| %>
    <% if resource.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

        <ul>
          <% resource.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form.hidden_field :user, value: current_spree_user %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="field">
      <label>Subcategory</label>
      <% subcategory_collection = [] %>
      <% Subcategory.where(active: true).each do |sub| %>
        <% subcategory_collection << ["#{sub.name}", "#{sub.id}"] %>
      <% end %>
      <div class="row text-left">
        <div class="form-group col-12">
          <%= form.collection_select(:subcategory_id, Subcategory.where(active: true), :id, :name, prompt: true) %>
        </div>
      </div> <!-- row -->
    </div>

    <div class="field">
      <%= form.label "What Is it?" %>
      <%= form.text_field :classification, class: "form-control", placeholder: "i.e. Downloadable PDF, Printable Checklist, etc." %>
    </div>

    <div class="field">
      <label>Uplaod Sample Image</label><br>
      <%= form.file_field :sample %>
    </div> <!-- col-12 -->

    <div class="field">
      <label>Upload Actual Document</label><br>
      <%= form.file_field :document %>
    </div> <!-- col-12 -->


    <div class="field">
      <%= form.check_box :active %>
      <%= form.label "Publish this Lead Magnet (aka non-draft)" %>
    </div>

    <div class="actions field text-center">
      <%= form.submit class: "btn" %>
    </div>
  <% end %>
</div>

app/views/resources/edit.html.erb
<header
  class="bgimage"
  style="background: url(<%= asset_url("tiretracks.jpg") %>); height: 200px">
</header>

<div class="background-white py-5">
  <div class="container">
    <div class="row">
      <h1>Edit <%= @resource.title %></h1>
    </div> <!-- info row -->
    <%= render 'form', resource: @resource %>
  </div> <!-- info row -->
</div> <!-- container -->



<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/resources/index.html.erb
<header
  class="bgimage"
  style="background: url(<%= asset_url("tiretracks.jpg") %>); height: 200px">
</header>

<div class="background-white py-5">
  <div class="container">


    <header class="text-center w-100">
      <h1>Useful Resources</h1>
    </header> <!-- info row -->


    <section class="row d-flex justify-content-center mt-3">
      <% if @resources.count == 0 %>
        <p>There are currently no resources in this category.  Check back soon!</p>
      <% else %>
        <% @resources.each do |resource| %>
          <%= render partial: "layouts/resource_card", locals: { resource: resource } %>
        <% end %>
      <% end %>
    </section> <!-- Grid row -->

  </div> <!-- container -->
</div> <!-- background -->


<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/resources/new.html.erb
<header
  class="bgimage"
  style="background: url(<%= asset_url("tiretracks.jpg") %>); height: 200px">
</header>

<div class="background-white py-5">
  <div class="container">
    <div class="row">
      <h1>Add a New Lead Magnet</h1>
    </div> <!-- info row -->
    <%= render 'form', resource: @resource %>
  </div> <!-- info row -->
</div> <!-- container -->



<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/resources/show.html.erb
<header
  class="bgimage"
  style="background: url(<%= asset_url("tiretracks.jpg") %>); height: 200px">
</header>

<div class="background-white py-5">
  <div class="container text-center pb-2">

      <% if current_spree_user && current_spree_user.admin? %>
        <p>
          <%= link_to 'Edit Resource', edit_resource_path(@resource) %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to 'Resource Manager', admin_resources_path %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to 'Resources Page', resources_path %>
        </p>
      <% end %>

      <h1 class="mb-0 thin"><%= @resource.title %></h1>
      <h3 class="mb-0 h4 font-weight-bold color-red"><%= @resource.classification %></h3>

      <p><em>
        <% if current_spree_user && current_spree_user.admin? %>
          <% if @resource.active %>Active<% else %>Inactive<% end %>
        <% end %>
      </em></p>


      <img src="<%= rails_blob_path(@resource.sample) %>" class="thumbnail mt-2 mb-4" alt="Sample <%= @resource.title %> Image">

      <p class=""><%= @resource.description %></p>

      <a href="<%= rails_blob_path(@resource.document) %>" class="btn btn-pink btn-md" target="_blank">Download</a>

  </div> <!-- container -->
</div> <!-- background white -->



<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>