config/routes.rb
Rails.application.routes.draw do
  get 'admin/blogs'
  get 'admin/resources'
  get 'admin/subcategories'
  get 'admin/subscribers'
  resources :blogs
  resources :resources
  resources :subscribers
  resources :subcategories
  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to
  # Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the
  # :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being
  # the default of "spree".
  mount Spree::Core::Engine, at: '/store', as: 'spree'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #  COSMETICS
  get 'home/index'
  root 'home#index'

  get 'home/info'
  get 'home/export'
  get 'home/kits'

  get 'kits/XR250_XR400'
  get 'kits/XR600'
  get 'kits/XR650L'
  get 'kits/polaris_key_covers'
  get 'kits/replacement'
  get 'kits/rear_fenders_1'
  get 'kits/rear_fenders_2'
  get 'kits/graphics'

  get 'other/xr400mx'

  # PHOTOS
  resources :photos
  put "photos/:id/approve" => "photos#approve", as: "approve_photo"
  put "photos/:id/unapprove" => "photos#unapprove", as: "unapprove_photo"

  # CONTACT US
  resources :contacts
  put "contacts/:id/archive" => "contacts#archive", as: "archive_contact"
  put "contacts/:id/unarchive" => "contacts#unarchive", as: "unarchive_contact"


end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :resource, optional: true
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]
  before_action :admin_only, only: [:destroy]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.order("created_at DESC")
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)
    existing = Subscriber.where(email: @subscriber.email).first

    if existing
      existing.resource_id_array << params[:resource_id]
      existing.save
      redirect_to resource_path(params[:resource_id], email: @subscriber.email)
    else
      @subscriber.resource_id_array << params[:resource_id]
      respond_to do |format|
        if @subscriber.save
          format.html { redirect_to resource_path(@subscriber.resource_id_array.last(), email: @subscriber.email) }
          format.json { render :show, status: :created, location: @subscriber }
        else
          format.html { render :new }
          format.json { render json: @subscriber.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def admin_only
    unless current_user && current_user.admin
      redirect_back(fallback_location: root_path)
      flash[:warning] = "Sorry, you must be an administrator to access that page."
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(
        :first_name,
        :email,
        :member,
        :unsubscribed,
        resource_id_array: []
      )
    end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= simple_form_for(subscriber) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <% if subscriber.errors.any? %>
    <ul>
      <% subscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-inputs row">
    <div class="col-6">
      <%= f.label "First Name" %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
    <div class="col-6">
      <%= f.label "Email" %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-actions text-center">
    <%= f.button :button, "Subscribe", class: "btn mt-4", type: "submit", name: "resource_id", value: resource_id %>
  </div>
<% end %>

app/views/subscribers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscribers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Email</th>
      <th>Customer</th>
      <th>Unsubscribed</th>
      <th>Resource id array</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.first_name %></td>
        <td><%= subscriber.email %></td>
        <td><%= subscriber.customer %></td>
        <td><%= subscriber.unsubscribed %></td>
        <td><%= subscriber.resource_id_array %></td>
        <td><%= link_to 'Show', subscriber %></td>
        <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
        <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscriber', new_subscriber_path %>



<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/subscribers/new.html.erb
<h1>New Subscriber</h1>

<%= render 'form', subscriber: @subscriber %>

<%= link_to 'Back', subscribers_path %>



<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @subscriber.first_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @subscriber.email %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @subscriber.customer %>
</p>

<p>
  <strong>Unsubscribed:</strong>
  <%= @subscriber.unsubscribed %>
</p>

<p>
  <strong>Resource id array:</strong>
  <%= @subscriber.resource_id_array %>
</p>

<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>



<script type="text/javascript">
  $(document).ready(function(){
    $(".footer").removeClass("top-shadow-inset");
  });
</script>